spring.application.name=time

spring.datasource.url=jdbc:postgresql://localhost:5432/time_sheets
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8092

spring.jpa.hibernate.ddl_auto=create